Traceback (most recent call last):
  File "/data/scratch/kvalem/projects/2023/pseudomonas_aeruginosa/preprocessing/20_analysis/bin/00_countmat.py", line 50, in <module>
    bioprod_gsea = pd.read_csv(gsea_bp , sep = "\t") 
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/kvalem/.conda/envs/2022-default-scanpy/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'hAO_inf_hAO_ctrl_GSEA_GO_BP.tsv'
